name: Daily Commit Workflow

on:
  schedule:
    - cron: '15 5 * * *'
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make daily update - 22f3000227@ds.study.iitm.ac.in
        run: |
          echo "Daily update at $(date -u)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "chore: daily update on $(date -u)"
          git push
